In [2]:
my_list = [1,2,3]



In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2) #give you numbers of two and two, etc the step size you want

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(0,5,100) #gets the number os spaces between numbers you want

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [22]:
np.eye(4) #single digit because need to be a square

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.84923125, 0.61806088, 0.91222191, 0.85607105, 0.55749633])

In [24]:
np.random.rand(5,5)

array([[0.2458213 , 0.05134485, 0.88208707, 0.02737889, 0.73929904],
       [0.37006036, 0.07628479, 0.53834802, 0.42228289, 0.69840099],
       [0.1234318 , 0.25064452, 0.69896078, 0.51865349, 0.32822309],
       [0.97393825, 0.63049676, 0.39365076, 0.42601939, 0.50456993],
       [0.77585076, 0.59738761, 0.10927412, 0.04968471, 0.11700377]])

In [25]:
np.random.randn(2)

array([-1.83724713, -0.41941394])

In [26]:
np.random.randn(4,4)

array([[-1.72110589, -0.73873801,  0.94520404,  0.39607354],
       [ 0.42464363, -0.83373884,  0.27345751, -0.55988399],
       [-1.52150874, -0.65059702, -0.76606924,  1.31159285],
       [ 0.74738131, -1.1902143 ,  1.75208438,  1.27962135]])

In [27]:
np.random.randint(1,100)

7

In [28]:
np.random.randint(1,100,10) #10 random integers

array([41,  4, 96, 41, 13, 32, 61, 54, 89, 11])

In [30]:
arr = np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr = np.random.randint(0,50,10)

In [33]:
ranarr

array([12,  7, 17, 11, 16,  7, 31, 14,  7,  4])

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
ranarr.max()

31

In [38]:
ranarr.min()

4

In [39]:
ranarr

array([12,  7, 17, 11, 16,  7, 31, 14,  7,  4])

In [40]:
ranarr.argmax()

6

In [41]:
ranarr.argmin()

9

In [42]:
arr.shape

(25,)

In [50]:
arr = arr.reshape(5,5)

In [51]:
arr.shape

(5, 5)

In [52]:
arr.dtype

dtype('int32')